language: python
sudo: false
cache: false
python:
    - '3.5'
env:
  global:
    PYTHONUNBUFFERED=yes
  matrix:
    - TOXENV=2.7-django1.10
    - TOXENV=2.7-django1.9
    - TOXENV=pypy-django1.10
    - TOXENV=pypy-django1.9
    - TOXENV=3.4-django1.10
    - TOXENV=3.4-django1.9
    - TOXENV=3.5-django1.11
    - TOXENV=3.5-django1.10
    - TOXENV=3.5-django1.9
    - TOXENV=flake8
    - TOXENV=flakeplus
    - TOXENV=apicheck
    - TOXENV=cov
before_install:
    - |
          if [ "$TOXENV" = "pypy" ]; then
            export PYENV_ROOT="$HOME/.pyenv"
            if [ -f "$PYENV_ROOT/bin/pyenv" ]; then
              cd "$PYENV_ROOT" && git pull
            else
              rm -rf "$PYENV_ROOT" && git clone --depth 1 https://github.com/yyuu/pyenv.git "$PYENV_ROOT"
            fi
            "$PYENV_ROOT/bin/pyenv" install "pypy-$PYPY_VERSION"
            virtualenv --python="$PYENV_ROOT/versions/pypy-$PYPY_VERSION/bin/python" "$HOME/virtualenvs/pypy-$PYPY_VERSION"
            source "$HOME/virtualenvs/pypy-$PYPY_VERSION/bin/activate"
          fi
install: travis_retry pip install -U tox
script: tox -v -- -v
after_success:
  - .tox/$TOXENV/bin/coverage xml
  - .tox/$TOXENV/bin/codecov -e TOXENV
